const nation = [
    {
        code: "en",
        name: "English",
        ename: "English",
        emojie: ":flag_gb:",
    },
    {
        code: "bg",
        name: "български език",
        ename: "Bulgarian",
        emojie: ":flag_bg:",
    },
    {
        code: "zh",
        name: "Chinese",
        ename: "Chinese",
        emojie: ":flag_cn:",
    },
    {
        code: "cs",
        name: "čeština",
        ename: "Czech",
        emojie: ":flag_cz:",
    },
    {
        code: "da",
        name: "Danmark",
        ename: "Danish",
        emojie: ":flag_dk:",
    },
    {
        code: "nl",
        name: "Nederlands",
        ename: "Dutch",
        emojie: ":flag_nl:",
    },
    {
        code: "et",
        name: "eesti keel",
        ename: "Estonian",
        emojie: ":flag_ee:",
    },
    {
        code: "fi",
        name: "Finnish",
        ename: "Finnish",
        emojie: ":flag_fi:",
    },
    {
        code: "fr",
        name: "Français",
        ename: "French",
        emojie: ":flag_fr:",
    },
    {
        code: "de",
        name: "Deutsch",
        ename: "German",
        emojie: ":flag_de:",
    },
    {
        code: "el",
        name: "Ελληνικά",
        ename: "Greek",
        emojie: ":flag_gr:",
    },
    {
        code: "hu",
        name: "magyar",
        ename: "Hungarian",
        emojie: ":flag_hu:",
    },
    {
        code: "id",
        name: "Indonesia",
        ename: "Indonesian",
        emojie: ":flag_id:",
    },
    {
        code: "it",
        name: "Italiano",
        ename: "Italian",
        emojie: ":flag_it:",
    },
    {
        code: "ja",
        name: "にほんご",
        ename: "Japanese",
        emojie: ":flag_jp:",
    },
    {
        code: "lt",
        name: "lietuvių kalba",
        ename: "Lithuanian",
        emojie: ":flag_lt:",
    },
    {
        code: "pl",
        name: "Polski",
        ename: "Polish",
        emojie: ":flag_pl:",
    },
    {
        code: "pt",
        name: "Português",
        ename: "Portuguese",
        emojie: ":flag_pt:",
    },
    {
        code: "ro",
        name: "limba română",
        ename: "Romanian",
        emojie: ":flag_ro:",
    },
    {
        code: "ru",
        name: "Русский",
        ename: "Russian",
        emojie: ":flag_ru:",
    },
    {
        code: "es",
        name: "Español",
        ename: "Spanish",
        emojie: ":flag_es:",
    },
    {
        code: "sv",
        name: "Swedish",
        ename: "Swedish",
        emojie: ":flag_se:",
    },
    {
        code: "lv",
        name: "Latvija",
        ename: "Latvia",
        emojie: ":flag_lv:",
    },
    {
        code: "sk",
        name: "Slovenská",
        ename: "Slovak",
        emojie: ":flag_sk:",
    },
    {
        code: "sl",
        name: "Slovenski",
        ename: "Slovenian",
        emojie: ":flag_si:",
    },
];


module.exports = nation;